<!-- Configuracion de los permisos y vistas -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <a class="navbar-brand" href="index-logged_in.php">
          <img src="img/logo-temp.png" title="Colombia Feels" alt="Colombia Feels" style="margin-top: -15px; height:50px;" class="img-rounded"/>
      </a>
  </div>
  
    <ul class="nav navbar-top-links navbar-right">
     <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i><i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a onclick="">
                                <i class="fa fa-user fa-fw"></i> Opciones del usuario
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="">
                                <i class="fa fa-sign-out fa-fw"></i> Cerrar sesión
                            </a>
                        </li>
                    </ul>
                </li>
    </ul>
      

<!-- Configuracion de los permisos y vistas -->  
 <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href=""><i class="fa fa-trophy fa-fw"></i> Mis insignias</a>
                        </li>                   
                        <li>
                            <a href=""><i class="fa fa-cubes fa-fw"></i> Caja de herramientas</a>
                        </li>
                        <li>
                            <a href=""><i class="fa fa-line-chart fa-fw"></i> Mi progreso</a>
                        </li>

                        <li>
                            <a href=""><i class="fa fa-users fa-fw"></i> Foros de discusión</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
  </nav>