<!-- Panel principal del Colombia Feels 1.0 -->
<!-- vista de cada uno de los modulos configurados en el panel-->
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Bienvenidos a Colombia Feels</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <!-- /.col-lg-12 -->
              <div class="col-lg-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    Un viaje por la memoria histórica
                  </div>
                  <div class="panel-body">
                    <p>Caja de herramientas: Un viaje por la memoria histórica. "Aprender la paz y desaprender la guerra”,
                      un instrumento pedagógico creado y consolidado entre el Centro Nacional de Memoria Histórica y el Ministerio de Educación Nacional
                      y apoyada por la Agencia de los Estados Unidos para el Desarrollo Internacional (USAID) y de la Organización Internacional para
                      las Migraciones (OIM), con el que se busca reconocer al sector educativo como un vehículo fundamental en la construcción de ciudadanía
                      y consciente de las afectaciones del conflicto armado.
                    </p>
                  </div>
                </div>
              </div>
              <!-- /.col-lg-12 -->                            
            </div>
</div>